#!/bin/sh

# default config
FIELDS=SSID,SECURITY,BARS
POSITION=0; XOFF=0; YOFF=0
MAGIC=-4
FONT="DejaVu Sans Mono 10"

# All sinks
audios=$(pactl list sinks | grep Name | awk '{print $2}')

LINENUM=$(echo "$audios" | wc -l)

# Select sink
audio=$(echo "$audios" | rofi -i -dmenu -p "Test" -lines $LINENUM -location "$POSITION" -yoffset "$YOFF" -xoffset "$XOFF" -font "$FONT")

if [[ $audio == "" ]]; then
  echo "No sink selected"
  exit 1
fi

pactl set-default-sink $audio

# Move current audio devices to this channel
pactl list | grep "Sink Input" | awk '{print $3}' | awk -F \# '{print $2}' | xargs -L1 -I{} pactl move-sink-input {} $(default_sink)
