#!/bin/sh
gputemp=$(nvidia-smi --format=nounits,csv,noheader --query-gpu=temperature.gpu)
if [ -z $gputemp ]; then
    gputemp=None
fi
if [ "$gputemp" -gt 0 ]; then
    echo "GPU: $gputemp°C"
else
    echo "$no nvidia driver installed"
fi
