#!/bin/sh

killall -q polybar
if type "xrandr"; then
  xrandr --query | grep " connected" | while read -r line; do
    primary=$(echo $line | grep "primary")
    if [ -z "$primary" ]; then
      MONITOR=$(echo $line | awk '{print $1}') polybar --reload general &
    else
      MONITOR=$(echo $line | awk '{print $1}') polybar --reload primary &
    fi
  done
else
  polybar --reload primary &
fi
