#!/bin/sh

killall -q polybar
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    echo $m
    if [ "$m" = "DVI-D-0" ]; then
      MONITOR=$m polybar --reload primary &
    else
      MONITOR=$m polybar --reload general &
    fi
  done
else
  polybar --reload primary &
fi
